version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./AuthService.Presentation/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ConnectionString=Host=db;Port=5432;Database=inventory_track_auth_service;Username=postgres;Password=CHEATS145
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHEATS145
      POSTGRES_DB: inventory_track_auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
